### ISSUE TITLE
hello作者，这好像有个bug

### ISSUE THREAD

**Issue by SAKURA-LBY** [kuaifengle/qiankun-vue3-tabsPage#2]
![20220511_215727](https://user-images.githubusercontent.com/57472755/167870736-85968a77-7aa9-4387-9843-99532a72ee57.gif)

**Comment by kuaifengle** [comment]
bug已解决,      createWebHistory的需求还要研究一下

**Comment by SAKURA-LBY** [comment]
大神加个好友呗，这个项目有些写法我理解的有点模糊。
